"""
ICD-10 Mapper - Maps SNOMED concepts to ICD-10 codes.

Uses pre-processed crosswalk (snomed_icd10_crosswalk.json) generated by
scripts/build_crosswalk.py.

Mapping logic:
1. Look up SNOMED code in crosswalk
2. Return all ICD-10 mappings with priorities
3. Rank by specificity (longer codes = more specific)
4. Set inference_strength based on mapping quality

Inference strength rules:
- "explicit": One-to-one mapping, map_priority=1, no rules
- "strong_suggestion": One-to-one mapping with rules, or highest priority in one-to-many
- "weak": Multiple mappings with same priority, or low priority mappings
"""

from typing import List, Optional, Dict, Tuple
from pathlib import Path
import json
import logging

from ..shared.models import ICD10Code, InferenceStrength

logger = logging.getLogger(__name__)


class ICD10Mapper:
    """
    ICD-10 mapper using SNOMED→ICD-10 crosswalk.
    """

    def __init__(
        self,
        crosswalk_path: Path,
        icd10_reference_path: Path
    ):
        """
        Initialize ICD-10 mapper.

        Args:
            crosswalk_path: Path to snomed_icd10_crosswalk.json
            icd10_reference_path: Path to icd10_diabetes_codes.json
        """
        self.crosswalk_path = Path(crosswalk_path)
        self.icd10_reference_path = Path(icd10_reference_path)

        # Data structures
        self.crosswalk: Dict[str, List[Dict]] = {}  # snomed_id -> list of mappings
        self.icd10_codes: Dict[str, Dict] = {}  # icd10_code -> code info

        # Load data
        self._load_crosswalk()
        self._load_icd10_reference()

    def _load_crosswalk(self):
        """Load SNOMED→ICD-10 crosswalk."""
        logger.info(f"Loading crosswalk from {self.crosswalk_path}")

        with open(self.crosswalk_path, 'r', encoding='utf-8') as f:
            data = json.load(f)

        self.crosswalk = data.get('mappings', {})

        logger.info(f"Loaded crosswalk with {len(self.crosswalk)} SNOMED concepts")

    def _load_icd10_reference(self):
        """Load ICD-10 code reference."""
        logger.info(f"Loading ICD-10 reference from {self.icd10_reference_path}")

        with open(self.icd10_reference_path, 'r', encoding='utf-8') as f:
            data = json.load(f)

        codes = data.get('codes', [])
        for code_data in codes:
            self.icd10_codes[code_data['code']] = code_data

        logger.info(f"Loaded {len(self.icd10_codes)} ICD-10 codes")

    def map_snomed_to_icd10(
        self,
        snomed_code: str,
        semantic_confidence: float = 1.0
    ) -> List[ICD10Code]:
        """
        Map SNOMED code to ICD-10 codes.

        Args:
            snomed_code: SNOMED CT concept ID
            semantic_confidence: Confidence from semantic resolver (0.0-1.0)

        Returns:
            List of ICD10Code objects, ranked by specificity and priority
        """
        # Look up in crosswalk
        mappings = self.crosswalk.get(snomed_code, [])

        if not mappings:
            logger.debug(f"No ICD-10 mapping found for SNOMED {snomed_code}")
            return []

        # Process each mapping
        icd10_results = []
        for mapping in mappings:
            icd10_code = mapping['icd10_code']
            map_group = mapping.get('map_group', 1)
            map_priority = mapping.get('map_priority', 1)
            map_rule = mapping.get('map_rule', '')
            map_advice = mapping.get('map_advice', '')

            # Get code details from reference
            code_info = self.icd10_codes.get(icd10_code)
            if not code_info:
                logger.warning(f"ICD-10 code {icd10_code} not in reference data")
                # Create minimal entry
                code_info = {
                    'code': icd10_code,
                    'display': icd10_code,
                    'billable': True,
                    'category': icd10_code[:3],
                    'hcc': False
                }

            # Determine inference strength
            inference_strength = self._determine_inference_strength(
                mappings=mappings,
                current_mapping=mapping,
                semantic_confidence=semantic_confidence
            )

            # Calculate combined confidence
            # Factors: semantic confidence, mapping priority, presence of rules
            mapping_confidence = self._calculate_mapping_confidence(
                map_priority=map_priority,
                has_rule=bool(map_rule),
                total_mappings=len(mappings)
            )
            combined_confidence = semantic_confidence * mapping_confidence

            # Specificity score (longer code = more specific)
            specificity = len(icd10_code.replace('.', ''))

            icd10_results.append(ICD10Code(
                code=code_info['code'],
                display=code_info['display'],
                confidence=combined_confidence,
                source='crosswalk',
                billable=code_info.get('billable', True),
                hcc=code_info.get('hcc', False),
                inference_strength=inference_strength,
                map_priority=map_priority,
                map_rule=map_rule if map_rule else None,
                specificity=specificity
            ))

        # Sort by: priority (asc), then specificity (desc), then confidence (desc)
        icd10_results.sort(
            key=lambda x: (x.map_priority, -x.specificity, -x.confidence)
        )

        return icd10_results

    def _determine_inference_strength(
        self,
        mappings: List[Dict],
        current_mapping: Dict,
        semantic_confidence: float
    ) -> InferenceStrength:
        """
        Determine inference strength for a mapping.

        Rules:
        - "explicit": One-to-one mapping, priority=1, no rules, semantic_confidence >= 0.9
        - "strong_suggestion": One-to-one with rules, or highest priority in one-to-many, semantic >= 0.7
        - "weak": Multiple mappings with same priority, or low semantic confidence
        """
        num_mappings = len(mappings)
        map_priority = current_mapping.get('map_priority', 1)
        map_rule = current_mapping.get('map_rule', '')

        # Explicit: one-to-one, no rules, high confidence
        if (num_mappings == 1 and
            map_priority == 1 and
            not map_rule and
            semantic_confidence >= 0.9):
            return "explicit"

        # Strong suggestion: one-to-one with rules, or highest priority
        if (num_mappings == 1 or
            (map_priority == 1 and semantic_confidence >= 0.7)):
            return "strong_suggestion"

        # Weak: everything else
        return "weak"

    def _calculate_mapping_confidence(
        self,
        map_priority: int,
        has_rule: bool,
        total_mappings: int
    ) -> float:
        """
        Calculate confidence score for a mapping.

        Factors:
        - Priority: Higher priority = higher confidence
        - Rules: Presence of rules reduces confidence (conditional mapping)
        - Total mappings: More alternatives = lower confidence per mapping
        """
        # Base confidence from priority
        priority_confidence = 1.0 / map_priority

        # Penalty for rules (conditional mapping)
        rule_penalty = 0.9 if has_rule else 1.0

        # Penalty for multiple mappings
        if total_mappings == 1:
            mapping_confidence = 1.0
        elif total_mappings <= 3:
            mapping_confidence = 0.8
        else:
            mapping_confidence = 0.6

        return priority_confidence * rule_penalty * mapping_confidence

    def batch_map(
        self,
        snomed_codes: List[Tuple[str, float]]
    ) -> List[List[ICD10Code]]:
        """
        Batch map multiple SNOMED codes.

        Args:
            snomed_codes: List of (snomed_code, semantic_confidence) tuples

        Returns:
            List of ICD-10 mapping results for each SNOMED code
        """
        results = []
        for snomed_code, confidence in snomed_codes:
            mappings = self.map_snomed_to_icd10(snomed_code, confidence)
            results.append(mappings)

        return results

    def get_icd10_info(self, icd10_code: str) -> Optional[Dict]:
        """Get detailed info for an ICD-10 code."""
        return self.icd10_codes.get(icd10_code)

    def is_billable(self, icd10_code: str) -> bool:
        """Check if ICD-10 code is billable."""
        code_info = self.icd10_codes.get(icd10_code)
        return code_info.get('billable', False) if code_info else False

    def is_hcc(self, icd10_code: str) -> bool:
        """Check if ICD-10 code is an HCC code."""
        code_info = self.icd10_codes.get(icd10_code)
        return code_info.get('hcc', False) if code_info else False


def test_icd10_mapper():
    """Test ICD-10 mapper with sample SNOMED codes."""
    # Paths (adjust as needed)
    crosswalk_path = Path("data/reference/snomed_icd10_crosswalk.json")
    icd10_reference_path = Path("data/reference/icd10_diabetes_codes.json")

    if not crosswalk_path.exists() or not icd10_reference_path.exists():
        print(f"✗ Required files not found")
        print(f"  Crosswalk: {crosswalk_path}")
        print(f"  ICD-10 reference: {icd10_reference_path}")
        print("Run data preparation scripts first.")
        return

    print("Testing ICD-10 Mapper")
    print("=" * 60)

    mapper = ICD10Mapper(
        crosswalk_path=crosswalk_path,
        icd10_reference_path=icd10_reference_path
    )

    # Sample SNOMED codes (diabetes-related)
    test_codes = [
        ("73211009", 1.0),   # Diabetes mellitus
        ("44054006", 0.95),  # Type 2 diabetes mellitus
        ("46635009", 0.90),  # Type 1 diabetes mellitus
        ("4855003", 0.85),   # Diabetic retinopathy
    ]

    for snomed_code, confidence in test_codes:
        print(f"\nSNOMED: {snomed_code} (confidence: {confidence})")
        results = mapper.map_snomed_to_icd10(snomed_code, confidence)

        if results:
            print(f"  Found {len(results)} ICD-10 mappings:")
            for icd10 in results:
                print(f"    {icd10.code} | {icd10.display[:50]}")
                print(f"      Confidence: {icd10.confidence:.3f}")
                print(f"      Inference: {icd10.inference_strength}")
                print(f"      Priority: {icd10.map_priority}, Specificity: {icd10.specificity}")
                if icd10.hcc:
                    print(f"      [HCC]")
        else:
            print(f"  No mappings found")


if __name__ == "__main__":
    # Configure logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )

    test_icd10_mapper()
